version: "3.8"
services:
  cliente:
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      - "home/app/node_modules"
      - "./:/home/app"