version: '3.8'

services:
  api-fc-1:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:5000"
    env_file: .env
    volumes:
      - .:/dados
    restart: always
  api-fc-2:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:5000"
    env_file: .env
    volumes:
      - .:/dados
    restart: always
  api-fc-3:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:5000"
    env_file: .env
    volumes:
      - .:/dados
    restart: always