# Generated by Django 4.2 on 2024-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterComprovantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('key_pagamento', models.IntegerField()),
                ('via_cliente', models.TextField()),
                ('via_estabelecimento', models.TextField()),
            ],
            options={
                'unique_together': {('ordem', 'key_pagamento')},
            },
        ),
    ]
