# Generated by Django 4.2 on 2024-09-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrinterComprovantes',
        ),
    ]
