# Generated by Django 4.0.2 on 2022-09-22 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('ordem', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('hour_at', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('M', 'Migrado para Protheus')], max_length=1)),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prot_pedidovenda', models.CharField(blank=True, max_length=8, null=True)),
                ('prot_filial', models.CharField(blank=True, max_length=4, null=True)),
                ('prot_nf', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpfvenda', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formapagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('DH', 'Dinheiro'), ('CC', 'Cartão de Credito'), ('CD', 'Cartão de Débito'), ('DP', 'Deposito em Conta')], max_length=2)),
                ('parcelas', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formpag_venda', to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Corpo_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripro', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_unitsis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitpro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_venda', to='produtos.produto')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_venda', to='vendas.venda')),
            ],
        ),
    ]
