# Generated by Django 4.2 on 2024-05-13 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vendas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0002_alter_produto_valor_unitpro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('ordem', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_at', models.DateField(default=datetime.date.today)),
                ('hour_at', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('M', 'Migrado para Protheus')], max_length=1)),
                ('total_venda', models.IntegerField()),
                ('prot_pedidovenda', models.CharField(blank=True, max_length=8, null=True)),
                ('prot_filial', models.CharField(blank=True, max_length=4, null=True)),
                ('prot_nf', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpfvenda', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formapagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('DH', 'Dinheiro'), ('CC', 'Cartão de Credito'), ('CD', 'Cartão de Débito'), ('DP', 'Deposito em Conta'), ('FO', 'Folha de Pagamento'), ('VE', 'Voucher Exagerado')], max_length=2)),
                ('parcelas', models.PositiveIntegerField()),
                ('valor', models.IntegerField()),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True)),
                ('nsu', models.CharField(blank=True, max_length=15, null=True)),
                ('autorizacao', models.CharField(blank=True, max_length=10, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=vendas.models.upload_to)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formpag_venda', to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Corpo_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripro', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_unitsis', models.IntegerField()),
                ('valor_unitpro', models.IntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_venda', to='produtos.produto')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_venda', to='vendas.venda')),
            ],
        ),
    ]
