# Generated by Django 4.0.2 on 2022-10-03 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='forma',
            field=models.CharField(choices=[('DH', 'Dinheiro'), ('CC', 'Cartão de Credito'), ('CD', 'Cartão de Débito'), ('DP', 'Deposito em Conta'), ('FO', 'Folha de Pagamento')], max_length=2),
        ),
        migrations.AlterField(
            model_name='venda',
            name='create_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
