# Generated by Django 4.2 on 2024-09-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formapagamento',
            old_name='nsu',
            new_name='nsu_host',
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='nsu_sitef',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
