# Generated by Django 4.2 on 2024-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_formapagamento_autorizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoSITEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(blank=True, null=True)),
                ('id_forma', models.IntegerField(blank=True, null=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('id_ref_cancelamento', models.IntegerField(blank=True, null=True)),
                ('nsu_host', models.CharField(blank=True, max_length=50, null=True)),
                ('nsu_sitef', models.CharField(blank=True, max_length=50, null=True)),
                ('autorizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
