# Generated by Django 4.0.2 on 2023-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_formapagamento_forma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpo_venda',
            name='valor_unitpro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corpo_venda',
            name='valor_unitsis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total_venda',
            field=models.IntegerField(),
        ),
    ]
