# Generated by Django 4.0.2 on 2023-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_corpo_venda_valor_unitpro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
