# Generated by Django 4.2 on 2024-09-26 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_recebimentositef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebimentositef',
            name='id_ref_cancelamento',
        ),
        migrations.AddField(
            model_name='recebimentositef',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recebimentositef',
            name='data_cupom',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='recebimentositef',
            name='nsu_host_cancelamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recebimentositef',
            name='nsu_sitef_cancelamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
