# Generated by Django 4.2 on 2024-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_remove_recebimentositef_id_ref_cancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentositef',
            name='forma',
            field=models.CharField(blank=True, choices=[('DH', 'Dinheiro'), ('CC', 'Cartão de Credito'), ('CD', 'Cartão de Débito'), ('DP', 'Deposito em Conta'), ('FO', 'Folha de Pagamento'), ('VE', 'Voucher Exagerado')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='recebimentositef',
            name='parcelas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recebimentositef',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
