# Generated by Django 4.2 on 2024-05-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_formapagamento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='autorizacao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='bandeira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='nsu',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
