# Generated by Django 4.2 on 2024-05-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_formapagamento_autorizacao_formapagamento_bandeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
