# Generated by Django 4.2 on 2024-05-12 00:36

from django.db import migrations, models
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_formapagamento_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='verificado',
            new_name='conciliado',
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.models.upload_to),
        ),
    ]
