# Generated by Django 4.0.2 on 2022-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('valor_unitsis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitpro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grupo', models.CharField(blank=True, max_length=30, null=True)),
                ('reposicao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaidaProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda', models.CharField(max_length=10)),
                ('descri', models.CharField(max_length=50)),
                ('visualizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
