# Generated by Django 4.2 on 2024-09-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariaveisdoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
    ]
